### ISSUE TITLE
Channels closing without stacktrace from iconv

### ISSUE THREAD

**Issue by lucasjohnston** [wclr/ts-node-dev#249]
## Issue description
I'm randomly getting channel closed errors with no useable stacktrace when running `ts-node-dev` like this:
```
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:705:16)
    at Object.exports.send (/PATH_TO_PROJECT/node_modules/ts-node-dev/lib/ipc.js:17:14)
    at /PATH_TO_PROJECT/node_modules/ts-node-dev/lib/wrap.js:88:9
    at Object.nodeDevHook [as .js] (/PATH_TO_PROJECT/node_modules/ts-node-dev/lib/hook.js:61:17)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.getCodec (/PATH_TO_PROJECT/node_modules/iconv-lite/lib/index.js:65:27)
    at Object.getDecoder (/PATH_TO_PROJECT/node_modules/iconv-lite/lib/index.js:127:23)
    at getDecoder (/PATH_TO_PROJECT/node_modules/raw-body/index.js:45:18)
    at readStream (/PATH_TO_PROJECT/node_modules/raw-body/index.js:180:15)
    at getRawBody (/PATH_TO_PROJECT/node_modules/raw-body/index.js:108:12)
    at read (/PATH_TO_PROJECT/node_modules/body-parser/lib/read.js:77:3)
    at jsonParser (/PATH_TO_PROJECT/node_modules/body-parser/lib/types/json.js:135:5)
    at Layer.handle [as handle_request] (/PATH_TO_PROJECT/node_modules/express/lib/router/layer.js:95:5)
```

I know this error is just a symptom of real problem in my code, but it's really hard to debug with no stacktrace or error message beyond this.

I'm guessing a type is going unchecked somewhere which is resulting in `iconv` erroring out rather than the error being caught + handled earlier.

## Context

*OS version (is it docker or host?), ts-node-dev version*
macOS 11.2,  ts-node-dev v1.1.1

*Did you try to run with [ts-node](https://github.com/TypeStrong/ts-node)*?
Yup, no error

*Did you try to run with `--files` option enabled?*
Yes

*Did you try to run with `--debug` option enabled?*
Yes

*Do you have a repro example (git repo) with simple steps to reproduce your problem?*
No - random

**Comment by zhirui1994** [comment]
I also have this problem when I start webpack-dev-server with ts-node-dev. For me, I restarted my computer and it worked. I guess it could be that the thread port is occupied by some program, which causes the ts-node-dev thread to fail to start.
