### ISSUE TITLE
Channel closed after some file change

### ISSUE THREAD

**Issue by willianhf** [wclr/ts-node-dev#266]
## Issue description
I have an `express` server setup, every time that I made a change to some file and some endpoint is called it throws the following error: 

```
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at new NodeError (node:internal/errors:329:5)
    at process.target.send (node:internal/child_process:724:16)
    at Object.exports.send (/Users/willianferreira/Projects/CargOn/microservices/extratta-api/node_modules/ts-node-dev/lib/ipc.js:17:14)
    at /Users/willianferreira/Projects/CargOn/microservices/extratta-api/node_modules/ts-node-dev/lib/wrap.js:88:9
    at Object.nodeDevHook [as .js] (/Users/willianferreira/Projects/CargOn/microservices/extratta-api/node_modules/ts-node-dev/lib/hook.js:61:17)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.getCodec (/Users/willianferreira/Projects/CargOn/microservices/extratta-api/node_modules/iconv-lite/lib/index.js:65:27)
```

## Context

Running the server with `ts-node-dev --transpile-only src/index.ts`

*OS version (is it docker or host?), ts-node-dev version*
macOS Big Sur `11.2.3`
ts-node-dev `^1.1.6`

*Did you try to run with [ts-node](https://github.com/TypeStrong/ts-node)*?
Yes.

*Did you try to run with `--files` option enabled?*
Yes.

*Did you try to run with `--debug` option enabled?*
Yes, the output with it:
```
[INFO] 08:16:01 Restarting: /Users/willianferreira/Projects/CargOn/microservices/extratta-api/src/services/SendExtratta.ts has been modified
[DEBUG] 08:16:01 /Users/willianferreira/Projects/CargOn/microservices/extratta-api/src/services/SendExtratta.ts compiled in 20 ms
[DEBUG] 08:16:01 Removing all watchers from files
[DEBUG] 08:16:01 Child is still running, restart upon exit
[DEBUG] 08:16:01 Disconnecting from child
[DEBUG] 08:16:01 Sending SIGTERM kill to child pid 9162
```

*Do you have a repro example (git repo) with simple steps to reproduce your problem?*
No.

**Comment by willianhf** [comment]
I find out that `prisma` was the problem and solved the issue adding the following, into my entry file.

```js
process.on('SIGTERM', () => {
  process.exit();
});
```

**Comment by krinoid** [comment]
Thanks @willianhf! I've had exactly the same problem and your solution definitely improved my workflow 🙂 🙌
