### ISSUE TITLE
ts-node-dev .fork() results in 100% cpu and an infinite loop in waiting for a compiled file

### ISSUE THREAD

**Issue by Rush** [wclr/ts-node-dev#283]
## Issue description

```ts
I am calling `child_process.fork(pathToATypescriptFile, ['--someParam'], {
  env: {
    ...process.env,
    MY_ENV_VAR: 'foo',
  }
});
```

What I'm seeing is 100% CPU usage. When debugged the same command with `--inspect` I see an infinite loop 
```bash
# ps aux | grep server-socket
rush     11915  100  0.0 588900 57128 pts/6    Rl+  23:35   0:26 /home/rush/.config/nvm/14.15.0/bin/node -r /tmp/ts-node-dev-hook-708417323754666.js --inspect -r tsconfig-paths/register /code/code2flow-magma-integration/node_modules/ts-node-dev/lib/wrap.js /code/server/server-socket.ts --colors
```
debug output is not showing anything interesting aside of:
```
[DEBUG] 23:35:31 /code/server/server-socket.ts added to watcher
```

When I added a breakpoint to by running the forked process by hand with the same parameter, it seems to be stuck in this `while(true)` loop:

![image](https://user-images.githubusercontent.com/115926/125024281-10419c80-e046-11eb-85bc-be5016ca2fe8.png)

Any idea how to debug, fix this?

## Context

*OS version (is it docker or host?), ts-node-dev version* host, 1.1.8

*Did you try to run with [ts-node](https://github.com/TypeStrong/ts-node)*? N/A

*Did you try to run with `--files` option enabled?* yes

*Did you try to run with `--debug` option enabled?* yes

*Do you have a repro example (git repo) with simple steps to reproduce your problem?* not yet

**Comment by Rush** [comment]
Any tips how to debug it further and possibly fix?

**Comment by ATheCoder** [comment]
Can you tell me how you connected a debugger to `ts-node-dev`?

**Comment by jannikkeye** [comment]
> Can you tell me how you connected a debugger to `ts-node-dev`?

@ATheCoder not OP but I'm doing it like  this `NODE_ENV=development ts-node-dev --inspect=127.0.0.1:9221 --exit-child -- ./src/myScript.ts`

**Comment by jannikkeye** [comment]
I've encountered this issue as well and have subsequently switched back to nodemon which works fine.

**Comment by Rush** [comment]
What I did to debug was to take what was in `ps aux` and and then re-run manually using `--inspect`.
```bash
node --inspect --max-old-space-size=2048 /code/project/node_modules/ts-node-dev/lib/wrap.js /code/project/worker.js --colors
```

**Comment by petewest-vocovo** [comment]
I'm also getting this problem.

**Comment by linkvt** [comment]
I also have this problem with a larger monorepo where we start multiple ts-node-dev watchers in parallel via tilt for the different services.
This issue only appears for me on macOS, it works fine on Ubuntu.

With some debug output and the `timeThreshold` in `child-require-hook.ts` set to `20_000` and a counter in the `while(true)` loop there I get the following output:

```
dbg child-require-hook.js compile_process.send {
  compile: '/path/to/monorepo/packages/library/src/util/some-url.transformer.ts',
  compiledPath: '/var/folders/48/hj0ldnq91kg8qn6hsx4ls22m0000gn/T/.ts-node1OZnQ1/compiled/___library_src_util_some_url_transformer_ts_33a17fac1d00b3b0aeccedefe6d3ed9a0b7f99e28deefc0a4a4ff223b65b67f3.js'
}
dbg child-require-hook.js waitForFile 100.000 loops for file /var/folders/48/hj0ldnq91kg8qn6hsx4ls22m0000gn/T/.ts-node1OZnQ1/compiled/___library_src_util_some_url_transformer_ts_33a17fac1d00b3b0aeccedefe6d3ed9a0b7f99e28deefc0a4a4ff223b65b67f3.js.done start 1658672928100 passed 726 timeThreshold 20000
Error: Could not require /var/folders/48/hj0ldnq91kg8qn6hsx4ls22m0000gn/T/.ts-node1OZnQ1/compiled/___library_src_util_some_url_transformer_ts_33a17fac1d00b3b0aeccedefe6d3ed9a0b7f99e28deefc0a4a4ff223b65b67f3.js.done
    at waitForFile (/private/var/folders/48/hj0ldnq91kg8qn6hsx4ls22m0000gn/T/ts-node-dev-hook-9647777766045864.js:42:19)
    at compile (/private/var/folders/48/hj0ldnq91kg8qn6hsx4ls22m0000gn/T/ts-node-dev-hook-9647777766045864.js:71:5)
    at Module.m._compile (/private/var/folders/48/hj0ldnq91kg8qn6hsx4ls22m0000gn/T/ts-node-dev-hook-9647777766045864.js:81:44)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at require.extensions..jsx.require.extensions..js (/private/var/folders/48/hj0ldnq91kg8qn6hsx4ls22m0000gn/T/ts-node-dev-hook-9647777766045864.js:126:20)
    at require.extensions.<computed> (/private/var/folders/48/hj0ldnq91kg8qn6hsx4ls22m0000gn/T/ts-node-dev-hook-9647777766045864.js:83:20)
    at Object.nodeDevHook [as .ts] (/path/to/monorepo/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
[DEBUG] 16:29:08 /path/to/monorepo/packages/library/src/util/some-url.transformer.ts added to watcher
dbg index.js compiler.compile {
  compile: '/path/to/monorepo/packages/library/src/util/some-url.transformer.ts',
  compiledPath: '/var/folders/48/hj0ldnq91kg8qn6hsx4ls22m0000gn/T/.ts-node1OZnQ1/compiled/___library_src_util_some_url_transformer_ts_33a17fac1d00b3b0aeccedefe6d3ed9a0b7f99e28deefc0a4a4ff223b65b67f3.js'
}
dbg compiler.js compile before _compile
dbg compiler.js compile_writeCompiled_outer /var/folders/48/hj0ldnq91kg8qn6hsx4ls22m0000gn/T/.ts-node1OZnQ1/compiled/___library_src_util_some_url_transformer_ts_33a17fac1d00b3b0aeccedefe6d3ed9a0b7f99e28deefc0a4a4ff223b65b67f3.js
[DEBUG] 16:29:08 /path/to/monorepo/packages/library/src/util/some-url.transformer.ts compiled in 3 ms
dbg compiler.js compile after _compile
[DEBUG] 16:29:08 Child error
[ERROR] 16:29:08 Error: Could not require /var/folders/48/hj0ldnq91kg8qn6hsx4ls22m0000gn/T/.ts-node1OZnQ1/compiled/___library_src_util_some_url_transformer_ts_33a17fac1d00b3b0aeccedefe6d3ed9a0b7f99e28deefc0a4a4ff223b65b67f3.js.done
[DEBUG] 16:29:08 Disconnecting from child
[DEBUG] 16:29:08 Sending SIGTERM kill to child pid 64763
dbg compiler.js compile_writeCompiled_inner /var/folders/48/hj0ldnq91kg8qn6hsx4ls22m0000gn/T/.ts-node1OZnQ1/compiled/___library_src_util_some_url_transformer_ts_33a17fac1d00b3b0aeccedefe6d3ed9a0b7f99e28deefc0a4a4ff223b65b67f3.js
dbg compiler.js compile_writeCompiled_inner_done /var/folders/48/hj0ldnq91kg8qn6hsx4ls22m0000gn/T/.ts-node1OZnQ1/compiled/___library_src_util_some_url_transformer_ts_33a17fac1d00b3b0aeccedefe6d3ed9a0b7f99e28deefc0a4a4ff223b65b67f3.js
[DEBUG] 16:29:08 Child exited with code null
```

It seems like the node event loop gets somehow stuck as indicated by the `writeCompiled` output being split into the output before `writeFile` in `compiler.ts` and the output running in its callback completely at the end.
Using `writeFileSync` in this place does not fix the issue, as the error still gets logged out before `writeCompiled`.

It seems that the `while (true)` in `child-require-hook.ts` loop plays a role here by keeping the event loop busy in some scenarios (many files? multiple node processes?) .

**Comment by doronrk** [comment]
This is a pretty serious issue imo. We're experiencing this too. I'm not sure how actively maintained ts-node-dev is but it would be great to get a fix for this.

**Comment by petewest-vocovo** [comment]
We have worked around this by statically importing the file before running it with fork, which seems to work most of the time, since ts-node-dev has a cache from compiling it previously 😬

**Comment by Hypnocrit** [comment]
I run a micro services environment locally for development and this issue tends to cap multiple processes at 100% constantly.  It's very very very annoying.    It's going to cause me to switch away soon.
