### ISSUE TITLE
tsNode.parse is not a function

### ISSUE THREAD

**Issue by cinderblock** [wclr/ts-node-dev#288]
## Issue description

I'm trying to run a simple app with `ts-node-dev`. It works under `ts-node` but fails with `ts-node-dev` with error:

```log
> ts-node-dev --rs --respawn daemon.ts "--debug"

[INFO] 11:35:10 ts-node-dev ver. 1.1.8 (using ts-node ver. 10.2.0, typescript ver. 4.3.5)
...\node_modules\ts-node-dev\lib\compiler.js:188
            compilerOptions: tsNode.parse(options['compiler-options']),
                                    ^

TypeError: tsNode.parse is not a function
    at registerTsNode (...\node_modules\ts-node-dev\lib\compiler.js:188:37)
    at Object.init (...\node_modules\ts-node-dev\lib\compiler.js:113:9)
    at Object.exports.runDev (...\node_modules\ts-node-dev\lib\index.js:256:14)
    at Object.<anonymous> (...\node_modules\ts-node-dev\lib\bin.js:134:4)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
```

## Context

*OS version (is it docker or host?), ts-node-dev version* Windows 11 x64

*Did you try to run with [ts-node](https://github.com/TypeStrong/ts-node)?* Yes

*Did you try to run with `--files` option enabled?* Yes

*Did you try to run with `--debug` option enabled?* Yes

*Do you have a repro example (git repo) with simple steps to reproduce your problem?* Not one I can share right now

**Comment by wclr** [comment]
Probably you somehow run ts-node-dev with ts-node 10, though it depends on v9
