### ISSUE TITLE
Issue Running With Yarn 3

### ISSUE THREAD

**Issue by luxiconn** [wclr/ts-node-dev#289]
## Issue description
I'm running into an issue when using ts-node-dev with Yarn 3

This is the command I'm trying to run. 

```
ts-node-dev --project tsconfig.json src/index.ts
```

The error I'm getting is this
```
C:\Projects\Web\wata\.pnp.cjs:11985
        if (fallbackReference === null || error === null) throw error || new Error(`Assertion failed: Expected an error to have been set`);
                                                          ^

Error: Your application tried to access src, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: src (via "src\index.ts")
Required by: C:\Projects\Web\wata\

    at internalTools_makeError (C:\Projects\Web\wata\.pnp.cjs:10747:34)
    at resolveToUnqualified (C:\Projects\Web\wata\.pnp.cjs:11968:21)
    at resolveRequest (C:\Projects\Web\wata\.pnp.cjs:12093:29)
    at C:\Projects\Web\wata\.pnp.cjs:12175:26
    at resolveRequest (C:\Projects\Web\wata\.yarn\__virtual__\ts-node-dev-virtual-3e4618e8f4\0\cache\ts-node-dev-npm-1.1.8-a4a6e3dc64-768a580621.zip\node_modules\ts-node-dev\lib\resolveMain.js:11:16)
    at Object.exports.resolveMain (C:\Projects\Web\wata\.yarn\__virtual__\ts-node-dev-virtual-3e4618e8f4\0\cache\ts-node-dev-npm-1.1.8-a4a6e3dc64-768a580621.zip\node_modules\ts-node-dev\lib\resolveMain.js:30:20)
    at Object.exports.runDev (C:\Projects\Web\wata\.yarn\__virtual__\ts-node-dev-virtual-3e4618e8f4\0\cache\ts-node-dev-npm-1.1.8-a4a6e3dc64-768a580621.zip\node_modules\ts-node-dev\lib\index.js:53:30)
    at Object.<anonymous> (C:\Projects\Web\wata\.yarn\__virtual__\ts-node-dev-virtual-3e4618e8f4\0\cache\ts-node-dev-npm-1.1.8-a4a6e3dc64-768a580621.zip\node_modules\ts-node-dev\lib\bin.js:134:4)   
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
```
## Context

*OS version (is it docker or host?), ts-node-dev version*
Windows 10
Typescript: 4.3.5
ts-node-dev: 1.1.8

*Did you try to run with [ts-node](https://github.com/TypeStrong/ts-node)*?
Yes, there is no issue with running

*Did you try to run with `--files` option enabled?*
Yes

*Did you try to run with `--debug` option enabled?*
Yes

**Comment by merceyz** [comment]
Workaround is to make the path relative
```
ts-node-dev --project tsconfig.json ./src/index.ts
```
