### ISSUE TITLE
[ERROR] Top Level Await

### ISSUE THREAD

**Issue by angelhdzmultimedia** [wclr/ts-node-dev#322]
## Issue description
I can't get **Top Level Await** to work with ts-node-dev, no matter what settings I use in package.json or tsconfig.json.

The only 2 things that worked were Babel compiler or Nodemon with `--loader ts-node/esm --experimental-specifier-resolution node`

I'm about to ditch ts-node-dev even after promoting it a lot, because it has issues benefiting from moden EcmaScript features.
Unless some kind soul provide a solution, of course. This is driving me crazy. Thank you.

## Context

*OS version (is it docker or host?) Windows 10 Home Build 19044, no docker

*ts-node-dev version: 2.0.0

*Did you try to run with [ts-node](https://github.com/TypeStrong/ts-node)*? Yes. It works with `ts-node-esm src/main.ts`.

*Did you try to run with `--files` option enabled?*

*Did you try to run with `--debug` option enabled?*

*Do you have a repro example (git repo) with simple steps to reproduce your problem?*  Don't have repro example because this issue happens in any fresh project I try.

**Comment by micchickenburger** [comment]
+1.  Here's a stack trace when passing the ESM flag both to ts-node-dev and to the child process:

```
NODE_OPTIONS=--es-module-specifier-resolution=node ts-node-dev --debug --respawn --es-module-specifier-resolution=node -- src/index.ts

(node:20) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
(Use `node --trace-warnings ...` to show where the warning was created)
Ignore watch: []
[INFO] 02:04:41 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.1, typescript ver. 4.7.4)
[DEBUG] 02:04:41 Starting child process -r /tmp/ts-node-dev-hook-05613959656589951.js --es-module-specifier-resolution=node /app/node_modules/ts-node-dev/lib/wrap.js src/index.ts
(node:27) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
(Use `node --trace-warnings ...` to show where the warning was created)
[DEBUG] 02:04:42 /app/src/index.ts added to watcher
Compilation error in /app/src/index.ts
Error: Must use import to load ES Module: /app/src/index.ts
    at Object.<anonymous> (/app/src/index.ts:1:7)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._compile (/app/node_modules/source-map-support/source-map-support.js:568:25)
    at Module.m._compile (/tmp/ts-node-dev-hook-05613959656589951.js:69:33)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-05613959656589951.js:114:20)
    at require.extensions.<computed> (/tmp/ts-node-dev-hook-05613959656589951.js:71:20)
    at Object.nodeDevHook [as .ts] (/app/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[DEBUG] 02:04:42 Child error
[ERROR] 02:04:42 Error: Must use import to load ES Module: /app/src/index.ts
[DEBUG] 02:04:42 Disconnecting from child
[DEBUG] 02:04:42 Sending SIGTERM kill to child pid 27
[DEBUG] 02:04:42 Child exited with code 0
```

**Comment by angelhdzmultimedia** [comment]
### Update
Besides it working with Babel, I achieved to make it working with `nodemon `and `ts-node`.

Install nodemon and ts-node and of course typescript, set `type: "module"` in `package.json`,
and set `tsconfig.json` to:

```json
{
  "compilerOptions": {
    "esModuleInterop": true,
    "moduleResolution": "Node",
    "module": "ESNext",
    "target": "ESNext"
  }
}
```

And then: `nodemon --exec node --loader ts-node/esm src/main.ts`

**Comment by OceanHL** [comment]
+1.   I am having the same problem, ts-node-dev does not support top-level await and the support for new ECMAScript features is very unfriendly. ts-node works perfectly.
```
[INFO] 16:45:00 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.1, typescript ver. 4.9.4)
[DEBUG] 16:45:00 Starting child process -r /tmp/ts-node-dev-hook-4801759276824187.js /mnt/g/hh-fcc/ethers-simple-storage/node_modules/ts-node-dev/lib/wrap.js depoly.ts
[DEBUG] 16:45:01 /mnt/g/hh-fcc/ethers-simple-storage/depoly.ts added to watcher
Compilation error in /mnt/g/hh-fcc/ethers-simple-storage/depoly.ts
Error: Must use import to load ES Module: /mnt/g/hh-fcc/ethers-simple-storage/depoly.ts
    at Object.<anonymous> (/mnt/g/hh-fcc/ethers-simple-storage/depoly.ts:1:7)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._compile (/mnt/g/hh-fcc/ethers-simple-storage/node_modules/source-map-support/source-map-support.js:568:25)
    at Module.m._compile (/tmp/ts-node-dev-hook-4801759276824187.js:69:33)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-4801759276824187.js:114:20)
    at require.extensions.<computed> (/tmp/ts-node-dev-hook-4801759276824187.js:71:20)
    at Object.nodeDevHook [as .ts] (/mnt/g/hh-fcc/ethers-simple-storage/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
[DEBUG] 16:45:01 Child error
[ERROR] 16:45:01 Error: Must use import to load ES Module: /mnt/g/hh-fcc/ethers-simple-storage/depoly.ts
[DEBUG] 16:45:01 Disconnecting from child
[DEBUG] 16:45:01 Sending SIGTERM kill to child pid 3417
[DEBUG] 16:45:01 Child exited with code 0
```
