### ISSUE TITLE
Error 'Exit status 1'

### ISSUE THREAD

**Issue by diego-duartera** [wclr/ts-node-dev#323]
## Issue description
There is no further details
Here's the error log file:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/duarte/.nvm/versions/node/v12.10.0/bin/node',
1 verbose cli   '/home/duarte/.nvm/versions/node/v12.10.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.10.3
3 info using node@v12.10.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle cm-bff@1.0.0~predev: cm-bff@1.0.0
6 info lifecycle cm-bff@1.0.0~dev: cm-bff@1.0.0
7 verbose lifecycle cm-bff@1.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle cm-bff@1.0.0~dev: PATH: /home/duarte/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/duarte/Desktop/panzura/cm-ui/cm-bff/node_modules/.bin:/home/duarte/.nvm/versions/node/v12.10.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
9 verbose lifecycle cm-bff@1.0.0~dev: CWD: /home/duarte/Desktop/panzura/cm-ui/cm-bff
10 silly lifecycle cm-bff@1.0.0~dev: Args: [ '-c', 'ts-node-dev --transpile-only  --debug ./src/index.ts' ]
11 silly lifecycle cm-bff@1.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle cm-bff@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: cm-bff@1.0.0 dev: `ts-node-dev --transpile-only  --debug ./src/index.ts`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/duarte/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:326:16)
13 verbose stack     at EventEmitter.emit (events.js:209:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/duarte/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:209:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid cm-bff@1.0.0
15 verbose cwd /home/duarte/Desktop/panzura/cm-ui/cm-bff
16 verbose Linux 5.15.0-41-generic
17 verbose argv "/home/duarte/.nvm/versions/node/v12.10.0/bin/node" "/home/duarte/.nvm/versions/node/v12.10.0/bin/npm" "run" "dev"
18 verbose node v12.10.0
19 verbose npm  v6.10.3
20 error code ELIFECYCLE
21 error errno 1
22 error cm-bff@1.0.0 dev: `ts-node-dev --transpile-only  --debug ./src/index.ts`
22 error Exit status 1
23 error Failed at the cm-bff@1.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

## Context

I'm running "npm run dev":

"dev": "ts-node-dev --transpile-only --no-notify --debug --files ./src/index.ts"

*OS version (is it docker or host?), ts-node-dev version*
OS Version: Ubuntu 22.04 LTS
ts-node-dev: ^1.1.6
node: v12.10.0

*Did you try to run with [ts-node](https://github.com/TypeStrong/ts-node)*?
Indeed

*Did you try to run with `--files` option enabled?*
Indeed

*Did you try to run with `--debug` option enabled?*
Indeed

*Do you have a repro example (git repo) with simple steps to reproduce your problem?*
No repo to test now.

Any idea on what is going on? I do not understand why it is failing.

Regards.
![Screenshot from 2022-07-25 16-49-26](https://user-images.githubusercontent.com/97259711/180879733-8a79a708-d601-4f0d-bfdb-ce453e8791ec.png)

**Comment by diego-duartera** [comment]
Already debugged this one, index.ts file error.
